{{- if and .Values.rbac.create .Values.rbac.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netfetch.fullname" . }}-clusterrole
rules:
  # Rules for core resources
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch", "create"]

  # Rules for NetworkPolicies in the networking.k8s.io API group
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create"]
{{- end }}
