# .goreleaser.yml
project_name: netfetch

# Build configuration
builds:
  - id: "netfetch"
    main: ./backend/main.go
    binary: netfetch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Additional build flags can be added here

# Archive configuration
archives:
  - id: "archive"
    builds:
      - netfetch
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

# Release configuration
release:
  github:
    owner: deggja
    name: netfetch
  draft: false
